config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :articles
  resources :categories, except: [:destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'  
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_many :articles, dependent: :destroy
  before_save { email.downcase! }
  has_secure_password

  validates :username,
            uniqueness: { case_sensitive: false },
            presence: true,
            length: { minimum: 5, maximum: 25 }

  validates :email,
            uniqueness: { case_sensitive: false },
            presence: true,
            format: { with: VALID_EMAIL_REGEX },
            length: { minimum: 5, maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?
    flash[:danger] = 'You must be logged in to perform this action'
    redirect_to root_path
  end

  def require_admin
    return if current_user.admin?    
    flash[:danger] = "Only admin users can perform this action"
    redirect_to root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index, show]
  before_action :require_same_user, only: %i[edit, update, destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was successfully created!'
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted!'
    redirect_to articles_path
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated!'
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    return if current_user.admin?
    if current_user != @article.user
      flash[:danger] = "You can only edit or delete your own article!"
      redirect_to root_path
    end    
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was successfully created!"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  private
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Welcome, #{user.username}!"
      session[:user_id] = user.id      
      redirect_to user_path(user)
    else
      flash.now[:danger] = "The e-mail or password is wrong."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've been logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :require_admin, only: %i[destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog, @#{@user.username}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    flash[:danger] = "#{@user.username} and all articles has been deleted."
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    return if current_user.admin?
    if current_user != @user
      flash[:danger] = "You can only edit your own account!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-sm-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by <%= article.user.username %>
              <%= time_ago_in_words(article.created_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %><br />
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %><br />
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, class: "form-control", rows: 8, placeholder: "Description", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Back to Articles", articles_path %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Articles</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.description %></p>
<p>Created by <%= link_to @article.user.username, users_path(@article.user) %></p>
<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
  <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-primary btn-sm" %>
  <%= link_to "Delete this Article", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
<% end %>
<%= link_to "View All Articles", articles_path, class: "btn btn-default btn-sm" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %><br />
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Back to Categories", categories_path %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/categories/index.html.erb
<h1 align="center">Categories</h1>
<%= will_paginate %>
<% @categories.each do |category| %>
<ul class="listing">
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <li class="article-title">
        <center><%= link_to "#{category.name}", category_path(category) %></center>
      </li>
    </div>
  </div>
</ul>
<% end %>
<%= will_paginate %>

app/views/categories/new.html.erb
<h1 align="center">New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center">Category</h1>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>This is Rails Blog</h1>
  <%= link_to "Sign Up", "#", class: "btn btn-primary btn-large" %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="#">The Complete Rails Developer Course</a> by <a href="#">Vinicius</a>
    </small>

    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
        <div class="<%= "alert alert-#{name}" %>" role="alert">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '🚀  Rails Blog', root_path, class: 'navbar-brand', id: 'logo' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= '(admin)' if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit your profile', edit_user_path(current_user) %></li>
              <li><%= link_to 'View your profile', user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>    
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Some errors prevented the form to be submitted!</h4>
        <ul class="list-group">
          <% obj.errors.full_messages.each do |error| %>
            <li class="list-group-item"><%= error %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %><br />
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %><br />
        </div>
        <div class="col-sm-8">
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %><br />
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary") %>
          <%= link_to "Back to users", users_path %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Bloggers</h1>
<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title"><%= link_to user.username, user_path(user) %></li>
          <li><%= pluralize(user.articles.count, "article") if user.articles.any? %></li>
          <% if logged_in? and current_user.admin? %>
          <li><%= link_to 'Delete this user', user_path(user), method: :delete, data: { confirm: "Deleting this user will delete all articles. Are you sure?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>  
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Showing <%= @user.username %> profile</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4" align="center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s Articles</h4>
<div align="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div align="center">
  <%= will_paginate @user_articles %>
</div>